server:
  port: 8868

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id:
            client-secret:
            redirect-uri:
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
