spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

server:
  port: 8868
logging.level:
  org.hibernate:
    SQL: debug
    type: trace